name: retro_box
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  device_preview: ^1.2.0
  dio: ^5.7.0
  data_connection_checker_tv: ^0.3.5-nullsafety
  shared_preferences: ^2.3.3
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  get_it: ^8.0.2
  http: ^1.2.2
  flutter_svg: ^2.0.16
  smooth_page_indicator: ^1.2.0+3
  provider: ^6.1.2
  image_picker: ^1.1.2
  loading_animation_widget: ^1.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo/retro_box.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/retro_box.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/tic_tac_toe/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900

    - family: Poppins-ExtraBold
      fonts: 
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 700
